### ISSUE TITLE
How do I use measurement.Because.He is not fixed

### ISSUE THREAD

**Issue by yaobo-lab** [influxdata/influxdb-plugin-fluent#10]
How do I use measurement.Because.He is not fixed

**Comment by yaobo-lab** [comment]
https://github.com/fangli/fluent-plugin-influxdb

![image](https://user-images.githubusercontent.com/21329253/87114583-88df1300-c2a3-11ea-975b-93b57e776b86.png)

**Comment by bednar** [comment]
Hi @yaobo-lab,

If you don't specify the `measurement` the plugin will use  event `tag`.

Regards

**Comment by yaobo-lab** [comment]
> Hi @yaobo-lab,
> 
> If you don't specify the `measurement` the plugin will use event `tag`.
> 
> Regards

Can I use the data I define.? because,  many apps log  come from a tag

for example:

![image](https://user-images.githubusercontent.com/21329253/87262085-2f692500-c4eb-11ea-8669-79edc0cf20bb.png)

in k8s all pod log come from a tag。

**Comment by bednar** [comment]
> Can I use the data I define.? because, many apps log come from a tag
> 
> for example:
> 
> ![image](https://user-images.githubusercontent.com/21329253/87262085-2f692500-c4eb-11ea-8669-79edc0cf20bb.png)
> 
Yes, it is valid configuration. Your measurement name will be: `application_name`.
