### ISSUE TITLE
Not writing to influxdbv2.

### ISSUE THREAD

**Issue by thisisloze** [influxdata/influxdb-plugin-fluent#20]
__Steps to reproduce:__
Here is my fluentD log and the connection is succesful to influxdbv2
but nothing is being written.

`
<source>
  @type forward
  port 24224
</source>

<match *.*.**>
  @type stdout
</match>

<match *.*.*>
  @type influxdb2
  url https://localhost:8086
  token 1zxSRbmOX2SJDkY1nXvO__2mq8Ov5ZFx-Wz-SNkfn7NBnpQDTTxtmKrSsAx6i8bwVCVCnKT2fEwmu8Gbu_SU2A==
  bucket binanceOps
  org btm
  use_ssl false
  measurement quote
</match>
`

__Expected behavior:__
It should write to influxdb. the record.

__Actual behavior:__
Nothing.

__Specifications:__
 - Client Version: latest
 - InfluxDB Version: 2.03
 - Platform: Ubuntu 18.04

**Comment by bednar** [comment]
Hi @thisisloze,

thanks for using our fluentd plugin.

Is your url correct? You turned off the `ssl` by: `use_ssl false`. Did you try the url without `https` - http://localhost:8086?

Could you please share a debug output of plugin?

```xml
<match ..*>
   @type influxdb2
   @log_level debug
```

Regards
