### ISSUE TITLE
Msgpack Support

### ISSUE THREAD

**Issue by s-g-r** [influxdata/influxdb-plugin-fluent#29]
__Proposal:__
Support or documentation for msgpack

__Current behavior:__
I am unsure if this plugin supports message pack, while in your examples you have attached a regex parser to a filter block, it doesn't look like that is applicable for msgpack from the fluent docs. 

__Desired behavior:__
Some way of parsing the msgpack format so that it can be ingested through the influxdb plugin.

__Alternatives considered:__
There may be alternative ways to complete this with vanilla fluentd configs that I can't find examples for, that a more experienced fluentd user could point to.

__Use case:__
Many of the client libraries use the message pack format such as [fluent-logger-python](https://github.com/fluent/fluent-logger-python/blob/ace80f4c2bd0020fc16891440243663c612dd01e/fluent/sender.py#L131).

**Comment by s-g-r** [comment]
The record that is being sent for example is like this:

('my-app.tag', 1635537121, {'field_key_foo': 'foo', 'value_key_bar': 'bar'})

and then is put through message pack via the client library here to result in this being sent to the forward type

b'\x93\xaamy-app.tag\xcea|P\xe1\x82\xadfield_key_foo\xa3foo\xadvalue_key_bar\xa3bar'

From the docs forward then automatically interprets this as [tag, time, record](https://github.com/fluent/fluentd/wiki/Forward-Protocol-Specification-v1#event-modes). From your current examples you use a string that has the key_name specified in the string to then apply your parser to it, however it is not clear what to do in this situation when your record is of an unpacked JSON.

**Comment by bednar** [comment]
The record is pairs of keys(String) and values(Object), you can use keys from your record. Something like:

```yaml
<store>
    @type influxdb2
    url http://influxdb_v2:8086
    token my-token
    bucket my-bucket
    org my-org
    use_ssl false
    time_precision s
    tag_keys ["value_key_bar"]
    field_keys ["field_key_foo"]
    <buffer tag>
      @type memory
      flush_interval 5
    </buffer>
  </store>
```

**Comment by s-g-r** [comment]
Apologies, I haven't been able to get back to this until later this week. I think I have narrowed down the problem, as mentioned above I have used many different combinations of the store function, including the original example set out like you have in your most recent comment. I believe I have narrowed the problem to the event timestamp, it appears that each new event does not get listed with its latest time stamp, and instead gets over written. I am using the default ns time setting for the plugin. For clarity here are some logs from stdout.

2021-11-05 09:15:49.487727165 +0000 my.app: {"foo":74,"bar":23.65}
....
2021-11-05 09:15:49.818440437 +0000 my.app: {"foo":85,"bar":23.72}
....
2021-11-05 09:15:50.297166824 +0000 my.app: {"foo":98,"bar":24.40}
2021-11-05 09:15:50.320703506 +0000 my.app: {"foo":99,"bar":24.36}

which all end up in influx with the same _time key of 2021-11-05 09:15:50 UTC

and the config with;

```
<match my.app>
    @type copy
    <store>
      @type influxdb2
      url http://influx-test:8086
      token token_string
      bucket my_bucket
      org my_org
      use_ssl false
      tag_keys   ["foo"]
      field_keys ["bar"]
      <buffer tag>
        @type memory
        flush_interval 5
      </buffer>
    </store>
  <store>
    @type stdout
  </store>
</match>
```
What particular string format are you expecting for the plugin?

**Comment by bednar** [comment]
Thanks for detail explanation.

> Apologies, I haven't been able to get back to this until later this week. I think I have narrowed down the problem, as mentioned above I have used many different combinations of the store function, including the original example set out like you have in your most recent comment. I believe I have narrowed the problem to the event timestamp, it appears that each new event does not get listed with its latest time stamp, and instead gets over written. I am using the default ns time setting for the plugin. For clarity here are some logs from stdout.
> 
> 2021-11-05 09:15:49.487727165 +0000 my.app: {"foo":74,"bar":23.65} .... 2021-11-05 09:15:49.818440437 +0000 my.app: {"foo":85,"bar":23.72} .... 2021-11-05 09:15:50.297166824 +0000 my.app: {"foo":98,"bar":24.40} 2021-11-05 09:15:50.320703506 +0000 my.app: {"foo":99,"bar":24.36}
> 
> which all end up in influx with the same _time key of 2021-11-05 09:15:50 UTC
> 
> and the config with;
> 
> ```
> <match my.app>
>     @type copy
>     <store>
>       @type influxdb2
>       url http://influx-test:8086
>       token token_string
>       bucket my_bucket
>       org my_org
>       use_ssl false
>       tag_keys   ["foo"]
>       field_keys ["bar"]
>       <buffer tag>
>         @type memory
>         flush_interval 5
>       </buffer>
>     </store>
>   <store>
>     @type stdout
>   </store>
> </match>
> ```
> 
> What particular string format are you expecting for the plugin?

If there is no specified a `time_key`, the timestamp is taken from event time - https://github.com/fluent/fluentd/wiki/Forward-Protocol-Specification-v1#event-modes.

Can you enable debug logging on `influxdb2`? There will be a generated output from plugin.

> EDIT:
> 
> I have also tried to send an additional field and use the time_key parameter by making use of the [RFC3339](https://www.influxdata.com/blog/tldr-tech-tips-flux-timestamps/) time stamps. Note I set the time precision to ms with this.
> 
> 2021-11-05 10:04:43.617226839 +0000 my.app: {"foo":97,"bar":24.43,"time":"2021-11-05T10:04:43.617216Z"}
> 
> I get the following error,
> 
> unable to parse 'my.app foo=97 bar=24.43 2021-11-05T10:04:43.617216Z': bad timestamp
> 
> Using the unix timestamp method doesnt seem to work at all.

The plugin suppose that the field value for `time_key` is epoch timestamp or Ruby's Time object. It is nice catch... I will prepare improvement.

**Comment by bednar** [comment]
I've prepared a fixed version within #30 for `time_key` enhancement. Development version of the plugin will be available after #30 acceptance, stable version in regular release cycle.

**Comment by s-g-r** [comment]
Great thanks, I will pull the feature branch and test. Interestingly I also tried the the time_key with an epoch unix time with ns precision and it did not parse.  Will this fix also address the issue of improperly ingesting the event time? If not I might need to head over to fluent - logger for python.

**Comment by bednar** [comment]
> Will this fix also address the issue of improperly ingesting the event time?

No, I am not able to simulate this issue.

**Comment by bednar** [comment]
The plugin didn't capture the event time but only results of serialization into LineProtocol (try to enable `debug` mode). The plugin internally uses the [Fluent::EventTime](https://www.rubydoc.info/gems/fluentd/Fluent/EventTime) type which is able to handle the timestamp without UTC timezone symbol.

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
